        self.rvr.sensor_control.start(interval=100)
        self.rvr.enable_color_detection(is_enabled=True)
        self.rvr.enable_battery_voltage_state_change_notify(is_enabled=True)
        self.exit_flag = False
        self.command = None
        self.direction = None
        self.heading = None
        self.speed = None
        self.rvrBatteryPercentage = None
        self.rvrColor = None
        self.rvrTemps = None
        self.rvrAmbientLight = None
        self.rvrEncoders = None
        self.rvrX = None
        self.rvrY = None
        self.rvrZ = None
        self.rvrPitch = None
        self.rvrYaw = None
        self.rvrRoll = None
        self.last_command = None
        self.vidconnection = None
        self.commandconnection = None
        self.sensorconnection = None